apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-service
spec:
  serviceName: "sample-service"
  replicas: 3
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - name: sample-service
        image: sample-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000