apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  clusterIP: "None"  # Headless service
  selector:
    app: sample-service
  ports:
    - protocol: TCP
      name: '9000'
      port: 9000
      targetPort: 9000 
    - protocol: TCP
      name: '9001'
      port: 9001
      targetPort: 9000 
    - protocol: TCP
      name: '9002'
      port: 9002
      targetPort: 9000 